version: "3"

services:
    frontend:
        build:
            context: frontend/.
        restart: on-failure
        expose:
            - "5000"
    backend:
        build:
            context: backend/api/.
        restart: on-failure
        expose:
            - "8080"
    balancer:
        build:
            context: infra/nginx/.
        restart: on-failure
        ports:
             - "80:80"
        expose:
            - "80"
