// generated by go-codegen(https://github.com/nchern/go-codegen)
// You COULD edit this code it you really need it and know what are you doing

package store

import (
	"sync"

	"github.com/nchern/homevscorona/backend/api/pkg/model"
)

type StringEventPtrMapVisitor func(string, *model.Event) bool

type StringEventPtrMap interface {
	Each(visitor StringEventPtrMapVisitor)
	Get(key string) (v *model.Event, found bool)
	Set(key string, val *model.Event)
	Update(src map[string]*model.Event) StringEventPtrMap
	Remove(key string) bool
	Clone() StringEventPtrMap
}

type baseStringEventPtrMap struct {
	_map map[string]*model.Event
}

func NewStringEventPtrMap() StringEventPtrMap {
	res := &baseStringEventPtrMap{
		_map: map[string]*model.Event{},
	}
	return res
}

func NewStringEventPtrMapSyncronized() StringEventPtrMap {
	return &syncStringEventPtrMap{
		inner: NewStringEventPtrMap(),
	}
}

func (m *baseStringEventPtrMap) Get(key string) (v *model.Event, found bool) {
	v, found = m._map[key]
	return
}

func (m *baseStringEventPtrMap) Each(visitor StringEventPtrMapVisitor) {
	for k, v := range m._map {
		if !visitor(k, v) {
			return
		}
	}
}

func (m *baseStringEventPtrMap) Set(key string, val *model.Event) {
	m._map[key] = val
}

func (m *baseStringEventPtrMap) Update(src map[string]*model.Event) StringEventPtrMap {
	for k, v := range src {
		m._map[k] = v
	}
	return m
}

func (m *baseStringEventPtrMap) Remove(key string) bool {
	_, found := m._map[key]
	delete(m._map, key)

	return found
}

func (m *baseStringEventPtrMap) Clone() StringEventPtrMap {
	res := NewStringEventPtrMap()
	for k, v := range m._map {
		res.Set(k, v)
	}

	return res
}

type syncStringEventPtrMap struct {
	inner StringEventPtrMap

	mutex sync.RWMutex
}

func (m *syncStringEventPtrMap) Each(visitor StringEventPtrMapVisitor) {
	m.mutex.RLock()
	m.inner.Each(visitor)
	m.mutex.RUnlock()
}

func (m *syncStringEventPtrMap) Get(key string) (v *model.Event, found bool) {
	m.mutex.RLock()
	v, found = m.inner.Get(key)
	m.mutex.RUnlock()
	return
}

func (m *syncStringEventPtrMap) Set(key string, val *model.Event) {
	m.mutex.Lock()
	m.inner.Set(key, val)
	m.mutex.Unlock()
}

func (m *syncStringEventPtrMap) Update(src map[string]*model.Event) StringEventPtrMap {
	m.mutex.Lock()
	m.inner.Update(src)
	m.mutex.Unlock()

	return m
}

func (m *syncStringEventPtrMap) Remove(key string) bool {
	m.mutex.Lock()
	found := m.inner.Remove(key)
	m.mutex.Unlock()

	return found
}

func (m *syncStringEventPtrMap) Clone() StringEventPtrMap {
	m.mutex.RLock()
	r := m.inner.Clone()
	m.mutex.RUnlock()
	return r
}
